- src/GoalTracker.js
Sizzle needs the window object in order to work. However on the server side (during pre-rendering) window doesn't exist and so this check is required for universal apps to work.
> Added window check for server side rendering compatibility

- CHANGELOG.md
- README.md
- package.json
- src/Stream.js
- src/__tests__/Stream-test.js
When running this script in Internet Explorer, MS Edge, Safari <9, etc, you get an error when utilizing the Streaming API, as these browsers don't have `EventSource` defined. See [caniuse](http://caniuse.com/#feat=eventsource) for more information.
In addition, this wasn't clear or obvious at all from the README.
Obviously `EventSource` can be polyfilled (around ~25KB minified and gzipped with [eventsource](https://github.com/aslakhellesoy/eventsource) for example) but it seems safe and reasonable to just ignore streaming functionality in browsers without support (either native or through polyfill) for  `EventSource`.
The consumers of this client could also take special care to not use the Streaming API with non-compliant browsers, but this means the internal implementation of the client …
> Add guard around EventSource for browsers without support

- README.md
- src/index.js
This adds the all_flags method to the JS client. Unlike the server-side all_flags method, I've chosen to have this send analytics events. 
The server-side use case is to bootstrap flags, so it doesn't necessarily make sense to send events there. Here, I think there's a stronger argument for sending the events. We might possibly want to make it an option, though?
> Add all_flags method to the client

- src/Requestor.js
- src/__tests__/Requestor-test.js
The way cancellation was implemented here meant that it was possible for callbacks to never be called because the associated request was cancelled. I don't see a reason to keep this code right now.
> do not abort requests in requestor

- src/Requestor.js
- src/__tests__/Requestor-test.js
I did some more testing before deploying to our CDN and noticed that the ready event was being called twice. This change ensures we only ever call each callback once.
> avoid calling callbacks more than once when queued

- src/EventEmitter.js
Everything breaks when a specific event’s structure overwrites the entire event map
> Fix emitter.off

- src/__tests__/LDClient-test.js
- src/index.js
This change ensures that we do not overwrite settings cached in `localStorage` with `null`. This can happen when the connection to LD is broken.
I also added a few tests around `localStorage`, including one for the case where we do want to clear `localStorage` because it contains invalid JSON.
> Preserve cached settings when connection to LD is broken

- README.md
The links weren't rendering properly due to incorrect markdown.
> Fix "About LaunchDarkly" links in README

- package.json
- src/index.d.ts
Moves the typescript definitions into this repo.
This is intended to ensure that our typescript definitions are treated as "first class" and that they will be consistently updated in lock step with any api changes.
cc @jkodumal
> Move typescript definitions into npm module, fix up options

- README.md
This clarifies that the client-side ID must be used
> specify client instead of environment key

- README.md
http://docs.launchdarkly.com/docs/running-an-ab-test has moved to https://docs.launchdarkly.com/docs/running-ab-tests
> Fix a link to the docs that 404's

- src/__tests__/LDClient-test.js
- src/index.js
- src/messages.js
- src/store.js
@apucacao Here's an attempt at solving #55. I modeled the Store API based on [store.js](https://github.com/marcuswestin/store.js/).
I didn't take the liberty of adding a dependency to your SDK. However, as a consumer, I'd be open to that outcome, especially given the the lightweight and and robust nature of this particular library.
> Add safe wrappers around localStorage

- src/__tests__/LDClient-test.js
- src/index.js
- src/messages.js
The current `waitUntilReady()` method will never resolve if the 'ready' event fires after the client's code is run. This implementation will maintain the state of the promise and will always resolve even after the 'ready' event was emitted.
> Refactored `waitUntilReady()` to always resolve even after `ready` event was already emitted

- CHANGELOG.md
- package-lock.json
- package.json
- src/EventSerializer.js
- src/__tests__/LDClient-test.js
- src/errors.js
- src/index.js
- src/messages.js
- The `options` object now supports a `samplingInterval` property. If greater than zero, this causes a fraction of analytics events to be sent to LaunchDarkly: one per that number of events (pseudo-randomly). For instance, setting it to 5 would cause 20% of events to be sent on average.
> prepare 1.5.0 release

- CHANGELOG.md
- package.json
- src/Requestor.js
- src/Stream.js
- src/__tests__/LDClient-test.js
- src/__tests__/Stream-test.js
- src/__tests__/mockEventSource.js
- src/index.js
- src/utils.js
- Added support for a future update to LaunchDarkly that will deliver individual feature flag changes over the streaming connection as they occur, rather than requiring the client to re-request all flags for each change.
> prepare 1.6.0 release

- CHANGELOG.md
- package.json
- src/EventProcessor.js
- src/Requestor.js
- src/__tests__/EventProcessor-test.js
- src/__tests__/Requestor-test.js
- src/utils.js
- The client no longer creates an empty `XMLHttpRequest` at startup time (which could interfere with unit tests).
- The client now sends the SDK version to LaunchDarkly; previously it only sent the browser version. This will allow for better usage metrics in a future version of the LaunchDarkly UI.
> prepare 1.7.1 release

- CHANGELOG.md
- package.json
- src/EventProcessor.js
- src/__tests__/EventProcessor-test.js
- The client no longer creates an empty `XMLHttpRequest` at startup time (which could interfere with unit tests).
_This release was broken and should not be used._
> prepare 1.7.2 release

- CHANGELOG.md
- package.json
- src/Requestor.js
- src/index.js
- Fixed a bug that caused events _not_ to be sent if `options.sendEvents` was explicitly set to `true`.
- HTTP requests will no longer fail if there is a `charset` specified in the response's `Content-Type` header. ([#87](https://github.com/launchdarkly/js-client/issues/87))
> prepare 1.7.4 release

- .circleci/config.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/EventProcessor.js
- src/Requestor.js
- src/Store.js
- src/UserFilter.js
- src/index.js
- src/utils.js
- Removed two function calls that are not supported in Internet Explorer: `string.startsWith()` and `Object.assign()`.
> prepare 2.1.1 release

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.d.ts
- Fix the TypeScript definitions to properly support the ES default export.
> Prepare 2.1.2 release

- src/index.js
When upgrading from 1.7.0 to 2.1.2 we ran into an unexpected breaking change where although we bootstrap with localStorage, the flags would now be set to `null` leading to any calls to `variation` to throw until the client is fully ready. The behavior in the older version with the empty object allowed calls to `variation` to succeed before ready, but would simply use the default fallback value.
This change restores that old behavior.
> Ensure flags isn't set to null if bootstrapping

- CHANGELOG.md
- package.json
- src/index.d.ts
- New event `goalsReady` (and new method `waitUntilGoalsReady`, which returns a Promise based on that event) indicates when the client has loaded goals-- i.e. when it is possible for pageview events and click events to be triggered.
- Fixed a bug where calling `variation` would throw an error if the client was bootstrapped from local storage and there were no flags in local storage yet, and the initial HTTP request for flags from LaunchDarkly had not yet completed. (thanks, [mpcowan](https://github.com/launchdarkly/js-client/pull/97)!)
> prepare 2.2.0 release

- src/index.js
- If a polling request has failed due to an invalid environment key, calling `variation` now returns the default value; previously, it sometimes caused a null reference error.
> prepare 2.3.1 release

- src/index.d.ts
It looks like identify() function's callback is missing arguments definitions:
https://github.com/launchdarkly/js-client/blob/078467e47c37def50030d29176141b908a5539ca/src/index.js#L150
https://github.com/launchdarkly/js-client/blob/078467e47c37def50030d29176141b908a5539ca/src/utils.js#L54
> Update typings for identify() function

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/__tests__/LDClient-test.js
- src/index.js
- src/utils.js
- The result value of `identify()` (provided by either a promise or a callback, once the flag values for the new user have been retrieved) used to be a simple map of flag keys to values, until it was accidentally changed to an internal data structure in version 2.0.0. It is now a map of flag keys to values again, consistent with what is returned by `allFlags()`.
- Added TypeScript definitions for the result values of `identify()`. (Thanks, [1999](https://github.com/launchdarkly/js-client/pull/102)!)
- Documented all optional compatibility polyfills in `README.md`.
> prepare 2.4.1 release

- packages/ldclient-js-common/src/EventSender.js
- packages/ldclient-js-common/src/__tests__/EventSender-test.js
- packages/ldclient-js-common/src/__tests__/stubPlatform.js
- packages/ldclient-js/src/__tests__/browserPlatform-test.js
- packages/ldclient-js/src/browserPlatform.js
- If there are pending analytics events when the page is being closed, the SDK normally attempts to deliver them by making a synchronous HTTP request. Chrome, as of version 73, does not allow this and logs an error. An upcoming release will change how events are sent, but as a temporary measure to avoid these errors, the SDK will now simply discard any pending events when the page is being closed _if_ the browser is Chrome version 73 or higher. In other browsers, there is no change. Note that this means that in Chrome 73, some events may be lost; that was already the case. The purpose of this patch is simply to avoid triggering errors. ([#178](https://github.com/launchdarkly/js-client-private/pull/178))
> prepare 2.9.6 release

- packages/launchdarkly-react-client-sdk/src/utils.ts
`startsWith` is not IE 11 compatible, `indexOf` gets the job done
> Replace startsWith with indexOf - IE compatibility

- package-lock.json
- src/__tests__/LDClient-test.js
- src/index.js
Would like to have your opinion on this change. I have not confirmed if this solves my issue. However the test cases indicates that it does solve it.
**Requirements**
**Related issues**
Potential fix for #198 
**Describe the solution you've provided**
This sets the syncFlush flag back to false after we have flushed any events that needed to be flushed during the beforeunload event.
> Changes back to async flushes after the unload handler has completed

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- example/index.html
- typings.d.ts
**Requirements**
- [ n/a ] I have added test coverage for new or changed functionality
- [ X ] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ n/a ] I have validated my changes against all supported platform versions
**Related issues**
N/A
**Describe the solution you've provided**
Updated old URLs linking to the old docs site to current URLs for the current docs site.
**Describe alternatives you've considered**
N/A
**Additional context**
Some docs site URLs changed in 2020 when we changed hosting platforms and there have been IA changes since.
> Updates outdated Docs site URLs

- example/README.md
- example/example.js
- example/index.html
Thank you @RookieRick for making a [PR](https://github.com/launchdarkly/js-client-sdk/pull/270) for this issue. After discussing with the team, we decided to go with a tool that is more common for JavaScript developers instead of relying on python.
Also fixed the imports as we had a major version upgrade recently.
> fix: Embedded example's instruction and JS SDK version

- src/GoalManager.js
**Requirements**
- I did not add tests since this part of the code was already untested
- I did not validate changes against supported platform versions. This is a one-line change that is non-breaking - only additive. I wanted to put this PR up to show what was wrong. 
**Related issues**
https://github.com/launchdarkly/js-client-sdk/issues/275
**Describe the solution you've provided**
- This adds `context` as a key to the event payload for goal events. js-sdk-common [does not send](https://github.com/launchdarkly/js-sdk-common/blob/main/src/index.js#L145) any events without the context key in the payload. This means all goal events are currently not being sent in the latest SDK versions. 
- I left `contextKeys` in the event payload because I wasn't sure what exactly these were doing and …
> [Goal Manager] Add context as an event payload key as expected by js-sdk-common

- example/example.js
- package.json
- src/__tests__/LDClient-events-test.js
- src/__tests__/LDClient-test.js
- test-types.ts
- Added an optional timeout to the `waitForInitialization` method. When a timeout is specified the returned promise will be rejected after the timeout elapses if the client has not finished initializing within that time. When no timeout is specified the returned promise will not be resolved or rejected until the initialization either completes or fails.
- The track method now validates that the provided metricValue is a number. If a metric value is provided, and it is not a number, then a warning will be logged.
- Fixed the documentation for `evaluationReasons` for the `identify` method.
> prepare 3.3.0 release
